# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.group_running_less_than <- function(x, c, group_zeores = FALSE) {
    .Call(`_ACDm_group_running_less_than`, x, c, group_zeores)
}

.time_rolling_ntrans_left <- function(x, window_size) {
    .Call(`_ACDm_time_rolling_ntrans_left`, x, window_size)
}

.time_rolling_ntrans_right <- function(x, window_size) {
    .Call(`_ACDm_time_rolling_ntrans_right`, x, window_size)
}

.roll_time_mean <- function(x, width, align) {
    .Call(`_ACDm_roll_time_mean`, x, width, align)
}

.roll_time_count <- function(x, width, align) {
    .Call(`_ACDm_roll_time_count`, x, width, align)
}

.sumOuter <- function(d_LL_d_theta, d_psi_d_theta, psi) {
    .Call(`_ACDm_sumOuter`, d_LL_d_theta, d_psi_d_theta, psi)
}

.computeScoreTACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp) {
    .Call(`_ACDm_computeScoreTACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp)
}

.computeScoreTAMACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp) {
    .Call(`_ACDm_computeScoreTAMACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp)
}

.computeScoreLSNIACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp) {
    .Call(`_ACDm_computeScoreLSNIACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp)
}

.computeScoreSNIACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp) {
    .Call(`_ACDm_computeScoreSNIACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType, bp)
}

.computeScoreABACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreABACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreAMACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreAMACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreBCACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreBCACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreBACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreBACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreEXACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreEXACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreLACD2 <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreLACD2`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreLACD1 <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreLACD1`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

.computeScoreAACD <- function(x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType) {
    .Call(`_ACDm_computeScoreAACD`, x, param, order, mean, dist, distPara, newDayR, forceErrExpec, returnIndex, startType)
}

computeDurationsSubSec_wrap <- function(y, M, d, h, m, s, vol, price, open, close, durType_scalar, zeroDurHandeling_scalar, priceChange_scalar, cumVol_scalar) {
    .Call(`_ACDm_computeDurationsSubSec_wrap`, y, M, d, h, m, s, vol, price, open, close, durType_scalar, zeroDurHandeling_scalar, priceChange_scalar, cumVol_scalar)
}

computeDurationsShort_wrap <- function(y, M, d, h, m, s, open, close, zeroDurHandeling) {
    .Call(`_ACDm_computeDurationsShort_wrap`, y, M, d, h, m, s, open, close, zeroDurHandeling)
}

